fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.12.1
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    satellite_pe_tools: "#{source_dir}"
