fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    inifile: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
    provision: 'https://github.com/puppetlabs/provision.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    deploy_pe: "https://github.com/jarretlavallee/puppet-deploy_pe"
    ruby_task_helper: "https://git@github.com/puppetlabs/puppetlabs-ruby_task_helper"
  symlinks:
    satellite_pe_tools: "#{source_dir}"
