---
".gitignore":
  paths:
  - katello-default-ca.crt
".gitlab-ci.yml":
  delete: true
".travis.yml":
  deploy_to_forge:
    enabled: false
  docker_sets: []
  docker_defaults:
    bundler_args: ''
  secure: ''
  branches:
  - release
  simplecov: true
  notifications:
    slack:
      secure: >-
        MrOYy2pBqsgKqixc1njU7FuwYUIJNOXB+dEzyw3xNL3kWv6BpdTdj4k5TKEH+7FevfRwJVlZdtrRmil7TWJE7zDnD0B54HlF6YWWkUvMfP9O/oSR2tWnV6G7IqXS8Z9dxz8adLpT1aEfbdIcZrpHzXe3+QTT2r5sa96uuFbYMaqF5lEa6SshR1vO8NiaYWuMWP6ZDO96b5F+h4CQMZiuGEgCg3b0T/JCG5YKjBDlszF7vCRXjNl0+Nr+LMmrZV2ekqPNxxdDByuetOeHjqHGL1McASDIYqE9JWorYN1g5P/6M5+yjCmU1NSnIYslHlZxRYg6UjJns2rSarRKl7VS2xWdZbV17CfYXD1W0vYiHwD8UelpbwfUC6Evwe9fQ4fprOHBTRqr3ZcKSagJH21l7ryhN6NZNIg/NcWZH4r/8EkVXPri6G3tsyc5SLynBc0acrL5hs6++/CWePSkMBA+/H7XBhGQ8jrRLRSMl+VB5o6baBTzksaLjAQKPqIA4WLhqBEtT4+rm8QjzhvTcuTSkSwUcNX7N/5//m4Otva/NzJvnKGKiMHJUwayG4z4n1r9ergUae3ILRlQLrl+u2oSorXErCNnt9eA5kS3K910r6bQNSw5Zum7bt6QwNvmWBkDZuvs1NCRJrh7DA5NDHjjyVZ0buwVrDuer/PjZcS4KdQ=
appveyor.yml:
  delete: true
CONTRIBUTING.md:
  unmanaged: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
LICENSE:
  license_type: puppetpe
NOTICE:
  unmanaged: true
Rakefile:
  extras:
    - |
      require 'rspec/core/rake_task'
      namespace :satellite_pe_tools do
        RSpec::Core::RakeTask.new(:integration) do |t|
          t.pattern = 'spec/acceptance/**{,/*/**}/*_spec.rb'
          t.rspec_opts = "--tag integration"
        end
      end
spec/spec_helper.rb:
  allow_deprecations: true
  coverage_report: true
  mock_with: ":rspec"
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
