---
".gitignore":
  paths:
  - katello-default-ca.crt
".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true

Gemfile:
  optional:
    ":development":
    - gem: rest-client
      version: '~> 2.0'
LICENSE:
  license_type: puppetpe
NOTICE:
  unmanaged: true
Rakefile:
  extras:
    - |
      require 'rspec/core/rake_task'
      namespace :satellite_pe_tools do
        RSpec::Core::RakeTask.new(:integration) do |t|
          t.pattern = 'spec/acceptance/**{,/*/**}/*_spec.rb'
          t.rspec_opts = "--tag integration"
        end
      end
spec/spec_helper.rb:
  allow_deprecations: true
  coverage_report: true
  mock_with: ":rspec"
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/ci.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
.rubocop.yml:
  include_todos: true
