HOSTS:
  master:
    roles:
      - master
      - agent
      - dashboard
      - database
    platform: el-7-x86_64
    box : puppetlabs/centos-7.0-64-nocm
    hypervisor : vagrant_virtualbox
    pe_dir: http://neptune.puppetlabs.lan/2015.2/ci-ready
  satellite:
    roles:
      - satellite
    platform: el-7-x86_64
    box: rhel-70-x64-vbox-nocm
    box_url: http://int-resources.ops.puppetlabs.net/vagrant/puppetless_boxes/rhel-70.virtualbox.box
    hypervisor : vagrant_virtualbox
CONFIG:
  log_level: debug
  type: pe
