HOSTS:
  master.vm:
    roles:
      - master
      - agent
      - dashboard
      - database
    platform: el-7-x86_64
    box : puppetlabs/centos-7.0-64-nocm
    hypervisor : vagrant_virtualbox
    pe_dir: http://enterprise.delivery.puppetlabs.net/2017.1/ci-ready/
    pe_ver: '2017.1.0-rc3-4-g5264413'
  satellite.vm:
    roles:
      - satellite
    platform: el-7-x86_64
    box: rhel-72
    box_url: http://int-resources.ops.puppetlabs.net/vagrant/puppetless_boxes/rhel-7.2-x86_64.virtualbox.box
    hypervisor : vagrant_virtualbox
CONFIG:
  log_level: debug
  type: pe
  vagrant_memsize: 4096
